use_frameworks!

platform :ios, '9.0'

target 'PasswordEvaluator_Example' do
  pod 'PasswordEvaluator', :path => '../'

  target 'PasswordEvaluator_Tests' do
    inherit! :search_paths

    
  end
end
